### ISSUE TITLE
[Feature Request] Add community categorization

### ISSUE THREAD

**Issue by ramisedhom** [ganesshkumar/obsidian-plugins-stats-ui#31]
With the increasing number of Obsidian plugins, it becomes harder to find the proper plugin(s) for different needs. That's why I started [this shared airtable database](https://link.ramisedhom.com/Obsidian-Plugins-Categorization) to enable categorizing Obsidian plugins by the community.

I would like to merge the efforts with your Obsidian Plugins Stats, are you interested to do that?

**Comment by ganesshkumar** [comment]
Added categories for plugins but looks like people are not interested in categories as there are more than 2000+ plugins now.

- https://obsidian-plugin-stats.ganesshkumar.com/categories
- https://www.reddit.com/r/ObsidianMD/comments/1h3owwr/taking_a_first_step_at_categorizing_the_plugins/
