### ISSUE TITLE
[Feature Request] RSS, Atom, or equivalent feed(s)

### ISSUE THREAD

**Issue by axb21** [ganesshkumar/obsidian-plugins-stats-ui#33]
**Is your feature request related to a problem? Please describe**
It would be useful to have an RSS feed or equivalent of both new plugins as well as updated plugins. Users can then use their RSS reader of choice, or the Fraidycat plugin in the web browser, to be notified of changes. Unless I've missed it, the web site right now does not have a notification feature, leaving users with few options other than to visit the page over and over again (pull/polling based) rather than be notified of changes (push/subscription based).

**Describe the solution you'd like**
An RSS or Atom feed for "new plugins" and "updated plugins". A "stretch goal" would be RSS or Atom feeds for tags or individual plugins (might be weird and noisy, but perhaps there's a way to make it work).

**Describe alternatives you've considered**
Re-creating the data ingest parts of this site with the desired functionality, which seems like a needless waste of effort!

**Comment by ganesshkumar** [comment]
I have added the feed. https://obsidian-plugin-stats.ganesshkumar.com

**Comment by axb21** [comment]
@ganesshkumar sick, thank you!
