### ISSUE TITLE
Ask someone to revive this plugin

### ISSUE THREAD

**Issue by jcesguerram** [ganesshkumar/obsidian-plugins-stats-ui#45]
You should point to this plugin [Obsidian Itinerary](https://github.com/coddingtonbear/obsidian-itinerary) in some way and look for candidates to revive it It's such a cool plugin.
It would be great for project management

**Comment by ganesshkumar** [comment]
I see that you have posted in the plugin's github repo

**Comment by ganesshkumar** [comment]
I suggest posting it in the [Obsidian forum](https://forum.obsidian.md/) or [Obsidian Discord channel](https://discord.com/channels/686053708261228577/707816848615407697).

Closing it as you have already posted on the plugin's repo.
