### ISSUE TITLE
[BUG] Missing images from plugin pages

### ISSUE THREAD

**Issue by djasonic** [ganesshkumar/obsidian-plugins-stats-ui#49]
**Describe the bug**
Many plug in pages have missing image links from their documentation that was imported to the site.

**To Reproduce**

1. Go to '[dataview](https://obsidian-plugin-stats.ganesshkumar.com/plugins/dataview#Examples)'
2. Scroll down to 'Examples'
3. See error of missing images below the code block examples
4. Example missing image: https://obsidian-plugin-stats.ganesshkumar.com/plugins/docs/docs/assets/game.png

**Expected behavior**
Linked images appear inline within page layouts.

**Screenshots**
![Screenshot 2024-12-14 at 3 16 40 PM](https://github.com/user-attachments/assets/587aeeb1-c7f0-45ba-9f2d-9fc819f7bab8)

**Desktop (please complete the following information):**

- OS: [MacOS]
- Version [14.7]

**Additional context**
Unsure if it is feasible to fix by caching linked images on the site or by redirecting image links back to their original locations at the various source repos, but I did not see a bug report for this either.

**Comment by ganesshkumar** [comment]
Hi @djasonic, thanks for reporting this. The images in the README files are broken if relative urls are used. And I think almost everyone will prefer relative urls in README file. 

I have pushed a fix for this - https://obsidian-plugin-stats.ganesshkumar.com/plugins/dataview#Examples :)
