### ISSUE TITLE
[BUG] exception error get raised 

### ISSUE THREAD

**Issue by Isaac-rise** [ganesshkumar/obsidian-plugins-stats-ui#51]
Error: Application error: a client-side exception has occurred (see the browser console for more information).

**To Reproduce**
click into the search box and try to type something 

Page: https://obsidian-plugin-stats.vercel.app/plugins

**Comment by ganesshkumar** [comment]
Thanks for reporting this @Isaac-rise I was trying to improve the search by highlighting the search text in the plugin and broke something. I have pushed a fix already. It should be working now.

![image](https://github.com/user-attachments/assets/c547feeb-7ea8-4ede-b519-5b510835dbfd)
